/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogo_da_velha.apresentacao;

/**
 *
 * @author Rodrigo
 */
public class rankTeste extends javax.swing.JFrame {

    /**
     * Creates new form rankTeste
     */
    public rankTeste() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelPosicao1 = new javax.swing.JLabel();
        jLabelPosicao2 = new javax.swing.JLabel();
        jLabelPosicao3 = new javax.swing.JLabel();
        jLabelPosicao4 = new javax.swing.JLabel();
        jLabelPosicao5 = new javax.swing.JLabel();
        jLabelNick1 = new javax.swing.JLabel();
        jLabelNick2 = new javax.swing.JLabel();
        jLabelNick3 = new javax.swing.JLabel();
        jLabelNick4 = new javax.swing.JLabel();
        jLabelNick5 = new javax.swing.JLabel();
        jLabelPontuacao1 = new javax.swing.JLabel();
        jLabelPontuacao2 = new javax.swing.JLabel();
        jLabelPontuacao3 = new javax.swing.JLabel();
        jLabelPontuacao4 = new javax.swing.JLabel();
        jLabelPontuacao5 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitulo.setText("jLabel1");

        jLabelPosicao1.setText("jLabel1");

        jLabelPosicao2.setText("jLabel1");

        jLabelPosicao3.setText("jLabel1");

        jLabelPosicao4.setText("jLabel1");

        jLabelPosicao5.setText("jLabel1");

        jLabelNick1.setText("jLabel1");

        jLabelNick2.setText("jLabel1");

        jLabelNick3.setText("jLabel1");

        jLabelNick4.setText("jLabel1");

        jLabelNick5.setText("jLabel1");

        jLabelPontuacao1.setText("jLabel1");

        jLabelPontuacao2.setText("jLabel1");

        jLabelPontuacao3.setText("jLabel1");

        jLabelPontuacao4.setText("jLabel1");

        jLabelPontuacao5.setText("jLabel1");

        btnVoltar.setText("jButton1");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnSair.setText("jButton1");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPosicao1)
                            .addComponent(jLabelPosicao3)
                            .addComponent(jLabelPosicao2)
                            .addComponent(jLabelPosicao4)
                            .addComponent(jLabelPosicao5))
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNick1)
                            .addComponent(jLabelNick3)
                            .addComponent(jLabelNick2)
                            .addComponent(jLabelNick4)
                            .addComponent(jLabelNick5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPontuacao5)
                    .addComponent(jLabelPontuacao4)
                    .addComponent(jLabelPontuacao2)
                    .addComponent(jLabelPontuacao3)
                    .addComponent(jLabelPontuacao1))
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(btnVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelTitulo)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPosicao1)
                    .addComponent(jLabelNick1)
                    .addComponent(jLabelPontuacao1))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPosicao2)
                    .addComponent(jLabelNick2)
                    .addComponent(jLabelPontuacao2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPosicao3)
                    .addComponent(jLabelNick3)
                    .addComponent(jLabelPontuacao3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPosicao4)
                    .addComponent(jLabelNick4)
                    .addComponent(jLabelPontuacao4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPosicao5)
                    .addComponent(jLabelNick5)
                    .addComponent(jLabelPontuacao5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnSair))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rankTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rankTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rankTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rankTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rankTeste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabelNick1;
    private javax.swing.JLabel jLabelNick2;
    private javax.swing.JLabel jLabelNick3;
    private javax.swing.JLabel jLabelNick4;
    private javax.swing.JLabel jLabelNick5;
    private javax.swing.JLabel jLabelPontuacao1;
    private javax.swing.JLabel jLabelPontuacao2;
    private javax.swing.JLabel jLabelPontuacao3;
    private javax.swing.JLabel jLabelPontuacao4;
    private javax.swing.JLabel jLabelPontuacao5;
    private javax.swing.JLabel jLabelPosicao1;
    private javax.swing.JLabel jLabelPosicao2;
    private javax.swing.JLabel jLabelPosicao3;
    private javax.swing.JLabel jLabelPosicao4;
    private javax.swing.JLabel jLabelPosicao5;
    private javax.swing.JLabel jLabelTitulo;
    // End of variables declaration//GEN-END:variables
}
