/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogo_da_velha.apresentacao;

/**
 *
 * @author Rodrigo
 */
public class rankTeste extends javax.swing.JFrame {

    /**
     * Creates new form rankTeste
     */
    public rankTeste() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jPanelRank = new javax.swing.JPanel();
        jLabelPosicao1 = new javax.swing.JLabel();
        jLabelPosicao2 = new javax.swing.JLabel();
        jLabelPosicao3 = new javax.swing.JLabel();
        jLabelPosicao4 = new javax.swing.JLabel();
        jLabelPosicao5 = new javax.swing.JLabel();
        jLabelNick4 = new javax.swing.JLabel();
        jLabelNick5 = new javax.swing.JLabel();
        jLabelNick1 = new javax.swing.JLabel();
        jLabelNick2 = new javax.swing.JLabel();
        jLabelNick3 = new javax.swing.JLabel();
        jLabelPontuacao1 = new javax.swing.JLabel();
        jLabelPontuacao2 = new javax.swing.JLabel();
        jLabelPontuacao3 = new javax.swing.JLabel();
        jLabelPontuacao4 = new javax.swing.JLabel();
        jLabelPontuacao5 = new javax.swing.JLabel();
        jLabelPosicaoFixo = new javax.swing.JLabel();
        jLabelNickFixo = new javax.swing.JLabel();
        jLabelPontosFixo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jPanelRank.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rank", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Bright", 1, 24))); // NOI18N
        jPanelRank.setPreferredSize(new java.awt.Dimension(708, 350));

        jLabelPosicao1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelPosicao1.setText("1");

        jLabelPosicao2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelPosicao2.setText("2");

        jLabelPosicao3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelPosicao3.setText("3");

        jLabelPosicao4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelPosicao4.setText("4");

        jLabelPosicao5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelPosicao5.setText("5");

        jLabelNick4.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabelNick4.setText("jLabel1");

        jLabelNick5.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabelNick5.setText("jLabel1");

        jLabelNick1.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabelNick1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNick1.setText("jLabel1");

        jLabelNick2.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabelNick2.setText("jLabel1");

        jLabelNick3.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabelNick3.setText("jLabel1");

        jLabelPontuacao1.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabelPontuacao1.setText("jLabel1");

        jLabelPontuacao2.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabelPontuacao2.setText("jLabel1");

        jLabelPontuacao3.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabelPontuacao3.setText("jLabel1");

        jLabelPontuacao4.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabelPontuacao4.setText("jLabel1");

        jLabelPontuacao5.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabelPontuacao5.setText("jLabel1");

        jLabelPosicaoFixo.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabelPosicaoFixo.setText("Posição");

        jLabelNickFixo.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabelNickFixo.setText("Nick");

        jLabelPontosFixo.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabelPontosFixo.setText("Pontos");

        javax.swing.GroupLayout jPanelRankLayout = new javax.swing.GroupLayout(jPanelRank);
        jPanelRank.setLayout(jPanelRankLayout);
        jPanelRankLayout.setHorizontalGroup(
            jPanelRankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRankLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelPosicaoFixo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelNickFixo)
                .addGap(199, 199, 199)
                .addComponent(jLabelPontosFixo)
                .addGap(78, 78, 78))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addComponent(jSeparator4)
            .addGroup(jPanelRankLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanelRankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelPosicao2)
                    .addComponent(jLabelPosicao1)
                    .addGroup(jPanelRankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelPosicao3)
                        .addComponent(jLabelPosicao4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelRankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRankLayout.createSequentialGroup()
                            .addComponent(jLabelNick1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(102, 102, 102))
                        .addGroup(jPanelRankLayout.createSequentialGroup()
                            .addGroup(jPanelRankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelNick3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelNick4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(103, 103, 103)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRankLayout.createSequentialGroup()
                        .addComponent(jLabelNick2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)))
                .addGroup(jPanelRankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPontuacao2)
                    .addComponent(jLabelPontuacao1)
                    .addComponent(jLabelPontuacao3)
                    .addComponent(jLabelPontuacao4))
                .addGap(73, 73, 73))
            .addComponent(jSeparator5)
            .addGroup(jPanelRankLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabelPosicao5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                .addComponent(jLabelNick5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(jLabelPontuacao5)
                .addGap(121, 121, 121))
        );
        jPanelRankLayout.setVerticalGroup(
            jPanelRankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRankLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelRankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPosicaoFixo)
                    .addComponent(jLabelNickFixo)
                    .addComponent(jLabelPontosFixo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPosicao1)
                    .addComponent(jLabelPontuacao1)
                    .addComponent(jLabelNick1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanelRankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNick2)
                    .addComponent(jLabelPontuacao2)
                    .addComponent(jLabelPosicao2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPosicao3)
                    .addComponent(jLabelNick3)
                    .addComponent(jLabelPontuacao3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelRankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNick4)
                    .addComponent(jLabelPontuacao4)
                    .addComponent(jLabelPosicao4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPosicao5)
                    .addComponent(jLabelNick5)
                    .addComponent(jLabelPontuacao5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelTitulo.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jLabelTitulo.setText("X-O CONFLICT");

        jLabelImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogo_da_velha/img/b48tdbdff1ux.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 284, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addGap(284, 284, 284))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelRank, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
                    .addComponent(jLabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelRank, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rankTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rankTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rankTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rankTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rankTeste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabelImg;
    private javax.swing.JLabel jLabelNick1;
    private javax.swing.JLabel jLabelNick2;
    private javax.swing.JLabel jLabelNick3;
    private javax.swing.JLabel jLabelNick4;
    private javax.swing.JLabel jLabelNick5;
    private javax.swing.JLabel jLabelNickFixo;
    private javax.swing.JLabel jLabelPontosFixo;
    private javax.swing.JLabel jLabelPontuacao1;
    private javax.swing.JLabel jLabelPontuacao2;
    private javax.swing.JLabel jLabelPontuacao3;
    private javax.swing.JLabel jLabelPontuacao4;
    private javax.swing.JLabel jLabelPontuacao5;
    private javax.swing.JLabel jLabelPosicao1;
    private javax.swing.JLabel jLabelPosicao2;
    private javax.swing.JLabel jLabelPosicao3;
    private javax.swing.JLabel jLabelPosicao4;
    private javax.swing.JLabel jLabelPosicao5;
    private javax.swing.JLabel jLabelPosicaoFixo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelRank;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
